syntax = "proto3";
import "google/protobuf/timestamp.proto";

option java_multiple_files = true;
option java_package = "image.analyzer";
package imageAnalyzer;

service ImageAnalyser {

  //send image to server
  rpc publishImage(stream ImageSend) returns (ImageIdentifier);

  //retrieve image labels from server by given id
  rpc retrieveImageCharacteristics(ImageIdentifier) returns (ImageCharacteristics);

  //search images published under a given time interval
  rpc imagesSearch(SearchByDateIntervalAndLabel) returns (ImageNames);

}

message ImageIdentifier {
  string id = 1; // maybe change to int, to see which is better suited
}

//expected to be use as stream
message ImageSend {
  //oneof data{

  //HAS to include file type (png, jpg) to be stored correctly
  optional string name = 1;

  //divided in stream
  bytes chunk_data = 2;
  //}
}

message ImageCharacteristics {
  repeated string characteristic = 1;
}

message SearchByDateIntervalAndLabel {
  //lower end of date interval
  google.protobuf.Timestamp startDate = 1;
  //higher end of date interval
  google.protobuf.Timestamp endDate = 2;
  //label needs to match
  string label = 3;
}

message ImageNames {
  //list of names
  repeated string name = 1;
}